---
- name: Copy parquet data file
  copy:
    src: "{{ playbook_dir }}/../../data/yellow_tripdata_2025-02.parquet"
    dest: "{{ data_dir }}/yellow_tripdata_2025-02.parquet"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  when: "'producer' in group_names"

- name: Verify parquet file exists
  stat:
    path: "{{ data_dir }}/yellow_tripdata_2025-02.parquet"
  register: parquet_file
  when: "'producer' in group_names"

- name: Display parquet file info
  debug:
    msg: "Parquet file size: {{ (parquet_file.stat.size / 1024 / 1024) | round(2) }} MB"
  when: "'producer' in group_names and parquet_file.stat.exists"