---
#- name: Install Docker
#  apt:
#    name: docker.io
#    state: present
#  become: yes

- name: Install Docker Compose
  apt:
    name: docker-compose-plugin
    state: present
  become: yes

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Create kafka directory
  file:
    path: /opt/kafka
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Create kafka data directory with correct permissions
  file:
    path: /opt/kafka/data
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'
  become: yes

- name: Copy KRaft Kafka Docker Compose file
  template:
    src: kafka-kraft-compose.yml.j2
    dest: /opt/kafka/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Start Kafka with KRaft
  command: docker compose up -d
  args:
    chdir: /opt/kafka
  become: yes
  become_user: "{{ ansible_user }}"


- name: Wait for Kafka to be ready
  wait_for:
    port: "9092"
    host: "0.0.0.0"
    delay: 15
    timeout: 120