---
- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present
  become: yes

- name: Set JAVA_HOME environment variable
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME={{ java_home }}'
    create: yes
  become: yes

- name: Add Java to PATH
  lineinfile:
    path: /etc/environment
    line: 'PATH="$PATH:{{ java_home }}/bin"'
    create: yes
  become: yes

- name: Install SBT
  shell: |
    echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list
    echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
    apt-get update
    apt-get install -y sbt
  become: yes