all:
  children:
    zookeeper:
      hosts:
        vm1:
          ansible_host: 34.116.209.61
          internal_ip: 10.186.0.15
    kafka:
      hosts:
        vm2:
          ansible_host: 34.116.221.12
          internal_ip: 10.186.0.18
    producer:
      hosts:
        vm3:
          ansible_host: 34.116.160.137
          internal_ip: 10.186.0.16
    consumer:
      hosts:
        vm4:
          ansible_host: 34.118.5.225
          internal_ip: 10.186.0.17
  vars:
    ansible_user: a_grodowski_student_uw_edu_pl
    ansible_ssh_private_key_file: $HOME/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'