all:
  children:
    kafka:
      hosts:
        kafka:
          ansible_host: "{{ kafka_ip }}"
    spark-cluster:
      hosts:
        spark:
          ansible_host: "{{ spark_ip }}"
  vars:
    ansible_user: a_grodowski_student_uw_edu_pl
    ansible_ssh_private_key_file: $HOME/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'