---
- name: Deploy Kafka
  hosts: kafka
  become: no
  roles:
    - common
    - docker
    - kafka

- name: Configure Spark
  hosts: spark-cluster
  become: yes
  roles:
    - common
    - java-sbt
    - spark-app
