---
# Test to verify file paths are correct before deployment
- name: Test file paths
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Show current working directory
      debug:
        msg: "Current playbook dir: {{ playbook_dir }}"

    - name: Check if source files exist
      stat:
        path: "{{ item }}"
      register: file_check
      loop:
        - "{{ playbook_dir }}/../../src"
        - "{{ playbook_dir }}/../../build.sbt"
        - "{{ playbook_dir }}/../../project"
        - "{{ playbook_dir }}/../../data/yellow_tripdata_2025-02.parquet"

    - name: Display file check results
      debug:
        msg: "{{ item.item }}: {{ 'EXISTS' if item.stat.exists else 'MISSING' }}"
      loop: "{{ file_check.results }}"

    - name: List actual project structure
      shell: |
        echo "=== Project structure ==="
        find {{ playbook_dir }}/../.. -maxdepth 2 -type f -name "*.sbt" -o -name "*.scala" -o -name "*.parquet" | head -10
      register: project_structure

    - name: Show project structure
      debug:
        var: project_structure.stdout_lines