---
# Verify file copying and project setup
- name: Verify local source files exist
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check local source files
      find:
        paths: "{{ playbook_dir }}/../.."
        patterns: "build.sbt"
      register: local_build_sbt

    - name: Check local src directory
      find:
        paths: "{{ playbook_dir }}/../../src"
        recurse: yes
      register: local_src_files

    - name: Check local project directory
      find:
        paths: "{{ playbook_dir }}/../../project"
        recurse: yes
      register: local_project_files

    - name: Display local files
      debug:
        msg:
          - "Local build.sbt: {{ local_build_sbt.files | map(attribute='path') | list }}"
          - "Local src files: {{ local_src_files.files | length }} files"
          - "Local project files: {{ local_project_files.files | length }} files"

- name: Verify remote project setup
  hosts: producer:consumer
  tasks:
    - name: Check remote project directory
      find:
        paths: "{{ project_dir }}"
        recurse: yes
      register: remote_files

    - name: Check build.sbt specifically
      stat:
        path: "{{ project_dir }}/build.sbt"
      register: remote_build_sbt

    - name: Display remote files
      debug:
        msg:
          - "Remote project dir has {{ remote_files.files | length }} files"
          - "build.sbt exists: {{ remote_build_sbt.stat.exists }}"
          - "Remote files:"
          - "{{ remote_files.files | map(attribute='path') | list }}"