---
- name: Create project structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ project_dir }}/src"
    - "{{ project_dir }}/src/main"
    - "{{ project_dir }}/src/main/scala"
    - "{{ project_dir }}/src/main/scala/producer"
    - "{{ project_dir }}/src/main/scala/consumer"
    - "{{ project_dir }}/project"

- name: Copy individual source files
  copy:
    content: "{{ lookup('file', playbook_dir + '/../../' + item.src) }}"
    dest: "{{ project_dir }}/{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  loop:
    - { src: "build.sbt", dest: "build.sbt" }
    - { src: "src/main/scala/producer/TaxiTripStreamer.scala", dest: "src/main/scala/producer/TaxiTripStreamer.scala" }
    - { src: "src/main/scala/consumer/Consumer.scala", dest: "src/main/scala/consumer/Consumer.scala" }
    - { src: "project/build.properties", dest: "project/build.properties" }

- name: Verify project files copied
  find:
    paths: "{{ project_dir }}"
    recurse: yes
  register: project_files

- name: Display copied files
  debug:
    msg: "Project files: {{ project_files.files | map(attribute='path') | list }}"

- name: Update Kafka broker address in producer
  replace:
    path: "{{ project_dir }}/src/main/scala/producer/TaxiTripStreamer.scala"
    regexp: 'localhost:29092'
    replace: "{{ hostvars[groups['kafka'][0]]['internal_ip'] }}:{{ kafka_port }}"
  when: "'producer' in group_names"

- name: Update Kafka broker address in consumer
  replace:
    path: "{{ project_dir }}/src/main/scala/consumer/Consumer.scala"
    regexp: 'localhost:29092'
    replace: "{{ hostvars[groups['kafka'][0]]['internal_ip'] }}:{{ kafka_port }}"
  when: "'consumer' in group_names"

- name: Update parquet file path in producer
  replace:
    path: "{{ project_dir }}/src/main/scala/producer/TaxiTripStreamer.scala"
    regexp: '/home/agrodowski/Desktop/MIM/PDD/KAFKA/taxi-stream/data/'
    replace: "{{ data_dir }}/"
  when: "'producer' in group_names"

- name: Update log file paths in producer
  replace:
    path: "{{ project_dir }}/src/main/scala/producer/TaxiTripStreamer.scala"
    regexp: '/home/agrodowski/Desktop/MIM/PDD/KAFKA/taxi-stream/logs/'
    replace: "{{ logs_dir }}/"
  when: "'producer' in group_names"

- name: Update log file paths in consumer
  replace:
    path: "{{ project_dir }}/src/main/scala/consumer/Consumer.scala"
    regexp: '/home/agrodowski/Desktop/MIM/PDD/KAFKA/taxi-stream/logs/'
    replace: "{{ logs_dir }}/"
  when: "'consumer' in group_names"

- name: Check if build.sbt exists
  stat:
    path: "{{ project_dir }}/build.sbt"
  register: build_sbt_check

- name: Display build.sbt status
  debug:
    msg: "build.sbt exists: {{ build_sbt_check.stat.exists }}"

- name: Compile Scala project
  shell: sbt compile
  args:
    chdir: "{{ project_dir }}"
  register: sbt_compile
  changed_when: "'[success]' in sbt_compile.stdout"
  failed_when: sbt_compile.rc != 0
  when: build_sbt_check.stat.exists

- name: Display compilation result
  debug:
    msg: 
      - "SBT compile stdout:"
      - "{{ sbt_compile.stdout_lines }}"
      - "SBT compile stderr:"
      - "{{ sbt_compile.stderr_lines }}"
  when: build_sbt_check.stat.exists