version: '3.7'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: VM1_INTERNAL_IP:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://VM2_INTERNAL_IP:9092,PLAINTEXT_HOST://VM2_EXTERNAL_IP:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1