---
- name: Copy Zookeeper Docker Compose file
  template:
    src: zookeeper-compose.yml.j2
    dest: "{{ project_dir }}/docker/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Check if Docker Compose V2 is available
  shell: docker compose version
  register: docker_compose_v2
  ignore_errors: yes

- name: Start Zookeeper container (Docker Compose V2)
  shell: docker compose up -d
  args:
    chdir: "{{ project_dir }}/docker"
  when: docker_compose_v2.rc == 0

- name: Start Zookeeper container (Docker Compose V1)
  shell: docker-compose up -d
  args:
    chdir: "{{ project_dir }}/docker"
  when: docker_compose_v2.rc != 0

- name: Wait for Zookeeper to be ready
  wait_for:
    port: "{{ zookeeper_port }}"
    host: "{{ ansible_default_ipv4.address }}"
    delay: 10
    timeout: 60

- name: Verify Zookeeper is running
  command: docker ps
  register: docker_ps_output
  changed_when: false

- name: Display running containers
  debug:
    var: docker_ps_output.stdout_lines