---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install common packages
  apt:
    name:
      - curl
      - wget
      - unzip
      - git
      - htop
    state: present
  become: yes

- name: Create project directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ project_dir }}"
    - "{{ logs_dir }}"
    - "{{ data_dir }}"
    - "{{ project_dir }}/docker"