---
- name: Create application directory
  file:
    path: /opt/taxi-stream
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Clone TaxiStreamer repository from GitHub
  git:
    repo: https://github.com/AnthonyGrod/TaxiStreamer.git
    dest: /opt/taxi-stream
    force: yes
  become: yes

- name: Create producer run script
  template:
    src: run-producer.sh.j2
    dest: /opt/taxi-stream/run-producer.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'