---
- name: Create application directory
  file:
    path: /opt/taxi-stream
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Check if repository already exists
  stat:
    path: /opt/taxi-stream/.git
  register: repo_exists

- name: Clone TaxiStreamer repository from GitHub
  git:
    repo: https://github.com/AnthonyGrod/TaxiStreamer.git
    dest: /opt/taxi-stream
  become: yes
  when: not repo_exists.stat.exists

- name: Set correct ownership for repository
  file:
    path: /opt/taxi-stream
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
  become: yes

- name: Create producer run script
  template:
    src: run-producer.sh.j2
    dest: /opt/taxi-stream/run-producer.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'